name: Deploy Web App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .  # שורש המונורפו

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Set environment variables (NEXT_PUBLIC_API_URL)
        run: echo "NEXT_PUBLIC_API_URL=https://unity-voice-plan.azurewebsites.net/api" >> $GITHUB_ENV

      - name: Install all dependencies (root workspace)
        run: npm install

      - name: Build project
        run: npm run build --workspace=web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: |
            apps/web/.next/standalone
            apps/web/.next/static
            apps/web/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login 🔐
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'unity-voice-plan'
          slot-name: 'Production'
          package: .
